apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mt9ff5op5-dotnet-basic
  janus-idp.io/tekton: mt9ff5op5-dotnet-basic
  backstage.io/kubernetes-id: mt9ff5op5-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mt9ff5op5-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
